### ISSUE TITLE
Memory Leak in Message Delivery Content Cache

### ISSUE THREAD

**Issue by Wishmitha** [wso2/carbon-business-messaging#592]
**Description**

Memory usage telemetry (generated using JProfiler) for MB when transporting 10,000 1MB sized messages is given below.

![screenshot from 2017-10-06 10-31-03](https://user-images.githubusercontent.com/17608763/31263683-7d6b8bd0-aa81-11e7-819f-a7bb7721e7ad.png)

Here OutOfMemoryError exception occurs around the first red line displayed in the graph and a heap snapshot was taken around that point. 

![screenshot from 2017-10-06 10-14-32](https://user-images.githubusercontent.com/17608763/31263756-d8f5e6da-aa81-11e7-8b9e-084066214ad4.png)

According to the snapshot, most of the memory was occupied by the instances of _DisruptorCachedContent_ class. These instances are used in content cache (in _ContentCacheCreator_ class) to map the message content with message id. 

`private final Cache<Long, DisruptorCachedContent> contentCache;`

`contentCache = CacheBuilder.newBuilder().expireAfterWrite(expiryTime, TimeUnit.SECONDS).maximumSize(maximumSize).concurrencyLevel(1).build();`

The content cache was configured as follows in broker.xml
```
<contentCache>
     <maximumSize>100</maximumSize>
     <expiryTime>120</expiryTime>
</contentCache>
```

Also 5 content readers were configured to read content from the message store.

`<parallelContentReaders>5</parallelContentReaders>`

When analyzing the heap there are 5 instances of _ContentCacheCreator_ class which takes around 500 MB of retained size. 

![screenshot from 2017-10-06 11-06-02](https://user-images.githubusercontent.com/17608763/31264559-9d6860ba-aa87-11e7-9e39-df1948a0bccc.png)

It seems that each instance of _ContentCacheCreator_ maintains a cache with 100 (maximum size) _DisruptorCachedContent_ intances. (which is each about 1MB in size) For all 5 _ContentCacheCreator_  instances, it sums up about 500 MB of memory usage. And this memory cannot be cleared by the garbage collector as the content cache is configured to a maximum size of 100.
(Cache only replaces old content when 101st content arrives, and still maintains size of 100.)

Even when the garbage collector was triggered (using JProfiler) during the displayed lines in the telemetry, the instance count remains same for _DisruptorCachedContent_ and about 500MB of memeory is occupied.

When the, content cache is configured as below, the obtained memory is reduced as expected.

```
<contentCache>
     <maximumSize>50</maximumSize>
     <expiryTime>120</expiryTime>
</contentCache>
```
![screenshot from 2017-10-06 11-48-37](https://user-images.githubusercontent.com/17608763/31265418-5c24b770-aa8c-11e7-988a-e14498b02582.png)

As the maximum size of content cache is 50 now, only 250 instances of _DisruptorCachedContent_ are stored in the cache and only 250MB of memory is occupied.

Hence, it seems that the cause for the issue might be setting the eviction policy of the content cache to maximum size. As the cache maintains the maximum size regardless of the content size, the amount of memory consumed increases with the message size and eventually leads to an out memory scenario.

**Steps to Reproduce**

Run a JMS publisher and a subscriber to transport 10,000 1MB sized messages.

**Comment by a5anka** [comment]
Closing this issues since we can avoid this by altering the configurations.
